### PR TITLE
Add save option to app

### PR DESCRIPTION
**Pull request by rdodiya**
## Description of what I add

In MainActivity, add Save button save meme in firebase if user is logged in and register user & save memes if user is not logged in . Add SavedMemes activity which memes saved by user  in recyclerview.

## Issue I worked on

Issue : (https://github.com/clubgamma/Random-Meme-Generator-App/issues/31)

## Test app after changes:

https://user-images.githubusercontent.com/75332758/139128829-46ee687a-e5ac-4ac4-a973-91f0a9e5b3cd.mp4

https://user-images.githubusercontent.com/75332758/139128847-757a0d59-880c-4a00-973e-985473101718.mp4

 - [x] I have read the Code Of Conduct.

 - [x] I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by ak523** [comment]
@rdodiya there are some conflicts.

**Comment by rdodiya** [comment]
@ak523 checkout this out again ,conflicts are resolved

**Comment by ak523** [comment]
@rdodiya  still there are conflicts.

**Comment by ak523** [comment]
@rdodiya UI is a bit disrupted in the new changes you made.
image

**Comment by rdodiya** [comment]
> @rdodiya still there are conflicts.

That conflict is of space may be

**Comment by rdodiya** [comment]
> @rdodiya UI is a bit disrupted in the new changes you made. image

Ok I will resolve it or make new issue of make proper UI

**Comment by rdodiya** [comment]
@ak523 I resolve it and add a new commit "Update UI which was disrupted"

**Comment by ak523** [comment]
@rdodiya Thank you for contributing😊.
Happy coding🥳

**Pull request merged**
