### PR TITLE
Added app icon

### PR DESCRIPTION
**Pull request by Positron007**
Added the app icon for issue #7

### CODE REVIEW

**Comment by ak523** [comment]
@Positron007 I have tested your code in real device but for some reason the app launcher icon is not showing up.
WhatsApp Image 2021-10-03 at 3 45 43 PM

**Comment by Positron007** [comment]
But it is working fine in my device. 
!(https://user-images.githubusercontent.com/66166616/135761464-544a059f-3488-4536-b089-527b6f73370a.jpg)

**Comment by Positron007** [comment]
Hi! I just updated a file in my latest commit, hope it resolves any further issue.

**Comment by ak523** [comment]
@Positron007 Thanks for contributing😄.

**Pull request merged**
